#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/env.sh"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPOS_FILE="${REPOS_FILE:-$ROOT_DIR/repos.toml}"
REPOS_DIR="${REPOS_DIR:-$(cd "$ROOT_DIR/.." && pwd)}"
MARKER="# Generated by ubu-devshell/scripts/gen-patch-config.sh"

repo_entries() {
  awk '
    /^\[repos\][[:space:]]*$/ { in_repos = 1; next }
    /^\[/ { in_repos = 0 }
    in_repos && /^[[:space:]]*[A-Za-z0-9_]+[[:space:]]*=/ {
      key = $1
      sub(/[[:space:]]*=.*/, "", key)
      url = $0
      sub(/^[^=]*=[[:space:]]*"/, "", url)
      sub(/"[[:space:]]*$/, "", url)
      print key "\t" url
    }
  ' "$REPOS_FILE"
}

repo_dir_name() {
  local name="$1"
  printf '%s\n' "${name//_/-}"
}

is_tracked_config() {
  local repo_dir="$1"
  git -C "$repo_dir" ls-files --error-unmatch .cargo/config.toml >/dev/null 2>&1
}

is_generated_config() {
  local config="$1"
  [[ -f "$config" ]] && grep -Fq "$MARKER" "$config"
}

make_patch_body() {
  local consumer_dir="$1"
  local consumer_name="$2"
  "$PATCH_TOOL" "$consumer_dir" "$consumer_name" "$REPOS_FILE" "$REPOS_DIR" "$MARKER"
}

PATCH_TOOL="$("$SCRIPT_DIR/build-patch-config-tool.sh")"

echo "Generating local Cargo patch configs under $REPOS_DIR"
written=()
tmp_file=""
trap 'if [[ -n "$tmp_file" ]]; then rm -f -- "$tmp_file"; fi' EXIT

while IFS=$'\t' read -r name _url; do
  repo_dir="$REPOS_DIR/$(repo_dir_name "$name")"
  cargo_toml="$repo_dir/Cargo.toml"
  config_dir="$repo_dir/.cargo"
  config_file="$config_dir/config.toml"

  if [[ ! -f "$cargo_toml" ]]; then
    echo "skip: $repo_dir has no Cargo.toml"
    continue
  fi

  if is_tracked_config "$repo_dir"; then
    echo "refuse: $config_file is tracked by $repo_dir"
    exit 1
  fi

  if [[ -f "$config_file" ]] && ! is_generated_config "$config_file"; then
    echo "refuse: $config_file exists without the ubu-devshell generated marker"
    exit 1
  fi

  tmp_file="$(mktemp)"
  make_patch_body "$repo_dir" "$name" > "$tmp_file"
  if [[ ! -s "$tmp_file" ]]; then
    if [[ -f "$config_file" ]]; then
      rm -f -- "$config_file"
      echo "removed: $config_file (no sibling git dependencies)"
    fi
    rm -f -- "$tmp_file"
    tmp_file=""
    continue
  fi
  mkdir -p "$config_dir"
  if [[ -f "$config_file" ]] && cmp -s "$tmp_file" "$config_file"; then
    rm -f "$tmp_file"
    echo "unchanged: $config_file"
  else
    mv "$tmp_file" "$config_file"
    written+=("$config_file")
  fi
  tmp_file=""

  if git -C "$repo_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    if ! git -C "$repo_dir" check-ignore -q .cargo/config.toml; then
      echo "warn: $repo_dir should ignore .cargo/config.toml"
    fi
  fi
done < <(repo_entries)

if [[ "${#written[@]}" -eq 0 ]]; then
  echo "No files written."
else
  echo "Files written:"
  printf '%s\n' "${written[@]}"
fi
