#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPOS_FILE="${REPOS_FILE:-$ROOT_DIR/repos.toml}"
REPOS_DIR="${REPOS_DIR:-$(cd "$ROOT_DIR/.." && pwd)}"
MARKER="# Generated by ubu-devshell/scripts/gen-patch-config.sh"

repo_entries() {
  awk '
    /^\[repos\][[:space:]]*$/ { in_repos = 1; next }
    /^\[/ { in_repos = 0 }
    in_repos && /^[[:space:]]*[A-Za-z0-9_]+[[:space:]]*=/ {
      key = $1
      sub(/[[:space:]]*=.*/, "", key)
      url = $0
      sub(/^[^=]*=[[:space:]]*"/, "", url)
      sub(/"[[:space:]]*$/, "", url)
      print key "\t" url
    }
  ' "$REPOS_FILE"
}

repo_dir_name() {
  local name="$1"
  printf '%s\n' "${name//_/-}"
}

is_tracked_config() {
  local repo_dir="$1"
  git -C "$repo_dir" ls-files --error-unmatch .cargo/config.toml >/dev/null 2>&1
}

is_generated_config() {
  local config="$1"
  [[ -f "$config" ]] && grep -Fq "$MARKER" "$config"
}

make_patch_body() {
  local consumer_dir="$1"
  local consumer_name="$2"
  local name url dir rel_path

  printf '%s\n' "$MARKER"
  printf '%s\n' "# Local-only Cargo patches. Do not commit this file."
  printf '%s\n' "# Re-run from ubu-devshell when sibling paths change."
  printf '\n'

  while IFS=$'\t' read -r name url; do
    if [[ "$name" == "$consumer_name" ]]; then
      continue
    fi
    dir="$REPOS_DIR/$(repo_dir_name "$name")"
    if [[ ! -f "$dir/Cargo.toml" ]]; then
      continue
    fi
    rel_path="$(realpath --relative-to="$consumer_dir" "$dir")"
    printf '[patch."%s"]\n' "$url"
    printf '%s = { path = "%s" }\n\n' "$name" "$rel_path"
  done < <(repo_entries)
}

echo "Generating local Cargo patch configs under $REPOS_DIR"
written=()

while IFS=$'\t' read -r name _url; do
  repo_dir="$REPOS_DIR/$(repo_dir_name "$name")"
  cargo_toml="$repo_dir/Cargo.toml"
  config_dir="$repo_dir/.cargo"
  config_file="$config_dir/config.toml"

  if [[ ! -f "$cargo_toml" ]]; then
    echo "skip: $repo_dir has no Cargo.toml"
    continue
  fi

  if is_tracked_config "$repo_dir"; then
    echo "refuse: $config_file is tracked by $repo_dir"
    exit 1
  fi

  if [[ -f "$config_file" ]] && ! is_generated_config "$config_file"; then
    echo "refuse: $config_file exists without the ubu-devshell generated marker"
    exit 1
  fi

  mkdir -p "$config_dir"
  tmp_file="$(mktemp)"
  make_patch_body "$repo_dir" "$name" > "$tmp_file"
  if [[ -f "$config_file" ]] && cmp -s "$tmp_file" "$config_file"; then
    rm -f "$tmp_file"
    echo "unchanged: $config_file"
  else
    mv "$tmp_file" "$config_file"
    written+=("$config_file")
  fi

  if git -C "$repo_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    if ! git -C "$repo_dir" check-ignore -q .cargo/config.toml; then
      echo "warn: $repo_dir should ignore .cargo/config.toml"
    fi
  fi
done < <(repo_entries)

if [[ "${#written[@]}" -eq 0 ]]; then
  echo "No files written."
else
  echo "Files written:"
  printf '%s\n' "${written[@]}"
fi
