#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export CARGO_NET_OFFLINE=true

# All files, git indexes, and generated configs live in the temporary fixture.
python3 - "$SCRIPT_DIR/gen-patch-config.sh" <<'PY'
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import tomllib

generator = str(Path(sys.argv[1]).resolve())
marker = "# Generated by ubu-devshell/scripts/gen-patch-config.sh"

with tempfile.TemporaryDirectory(prefix="ubu-patch-test-") as temp:
    root = Path(temp) / "siblings with spaces"
    root.mkdir()
    repos_file = root / "repos.toml"
    repos_file.write_text('''[repos]
consumer = "https://example.invalid/consumer"
root_sibling = "https://example.invalid/root"
workspace_sibling = "https://example.invalid/workspace"
unused_sibling = "https://example.invalid/unused"
absent_sibling = "https://example.invalid/absent"
no_dependencies = "https://example.invalid/no-dependencies"
workspace_consumer = "https://example.invalid/workspace-consumer"
''')

    def write(path, text):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    def package(directory, name, extra=""):
        write(directory / "Cargo.toml", f'[package]\nname = "{name}"\nversion = "0.1.0"\nedition = "2021"\n{extra}')
        write(directory / "src/lib.rs", "")

    package(root / "root-sibling", "actual_root")
    workspace = root / "workspace-sibling"
    write(workspace / "Cargo.toml", '[workspace]\nresolver = "2"\nmembers = ["modules/*"]\n')
    package(workspace / "modules/alpha", "actual_alpha")
    package(workspace / "modules/beta", "actual_beta")
    # This virtual workspace has no members and must never be inspected/patched.
    write(root / "unused-sibling/Cargo.toml", '[workspace]\nmembers = []\n')
    package(root / "no-dependencies", "no_dependencies")
    consumer = root / "consumer"
    package(consumer, "consumer", '''
[dependencies]
root_alias = { package = "actual_root", git = "https://example.invalid/root" }
alpha_alias = { package = "actual_alpha", git = "https://example.invalid/workspace" }
absent = { git = "https://example.invalid/absent" }
unlisted = { git = "https://example.invalid/unlisted" }
[dev-dependencies]
actual_beta = { git = "https://example.invalid/workspace" }
[build-dependencies]
another_alpha = { package = "actual_alpha", git = "https://example.invalid/workspace" }
[target.'cfg(unix)'.dependencies]
target_root = { package = "actual_root", git = "https://example.invalid/root" }
''')
    wc = root / "workspace-consumer"
    write(wc / "Cargo.toml", '''[workspace]
resolver = "2"
members = ["member"]
[workspace.dependencies]
root_alias = { package = "actual_root", git = "https://example.invalid/root" }
''')
    package(wc / "member", "member", '''[dependencies]
root_alias.workspace = true
[build-dependencies]
beta_alias = { package = "actual_beta", git = "https://example.invalid/workspace" }
''')

    # Real temporary git repositories exercise index/ignore safety checks.
    def git(directory, *args):
        return subprocess.run(["git", "-C", str(directory), *args],
                              text=True, capture_output=True, check=True)

    git(consumer, "init", "-q")
    write(consumer / ".gitignore", ".cargo/config.toml\n")
    git(root / "no-dependencies", "init", "-q")
    config = consumer / ".cargo/config.toml"
    stale = root / "no-dependencies/.cargo/config.toml"
    write(stale, marker + '\n[patch."https://example.invalid/old"]\nold = { path = "../old" }\n')
    # Even obsolete virtual-manifest entries must not prevent package discovery.
    write(workspace / ".cargo/config.toml", marker + '\n[patch."https://example.invalid/bad"]\nbad = { path = "../unused-sibling" }\n')
    env = {**os.environ, "REPOS_DIR": str(root), "REPOS_FILE": str(repos_file),
           "CARGO_NET_OFFLINE": "true"}

    def generate(ok=True):
        result = subprocess.run(["bash", generator], cwd=root, env=env,
                                capture_output=True, text=True)
        assert (result.returncode == 0) == ok, result.stdout + result.stderr
        return result.stdout + result.stderr

    output = generate()
    assert "Files written:" in output
    parsed = tomllib.loads(config.read_text())["patch"]
    assert parsed["https://example.invalid/root"] == {"actual_root": {"path": "../root-sibling"}}
    print("PASS package-root dependency uses the actual package name and root directory")
    assert parsed["https://example.invalid/workspace"] == {
        "actual_alpha": {"path": "../workspace-sibling/modules/alpha"},
        "actual_beta": {"path": "../workspace-sibling/modules/beta"},
    }
    assert config.read_text().count('[patch."https://example.invalid/workspace"]') == 1
    print("PASS virtual workspace aliases resolve two packages under one URL block")
    for generated in root.glob("*/.cargo/config.toml"):
        assert "https://example.invalid/unused" not in generated.read_text()
        assert "unused_sibling" not in generated.read_text()
    print("PASS unused sibling emits no patch entry")
    assert "https://example.invalid/absent" not in parsed
    assert "https://example.invalid/unlisted" not in parsed
    print("PASS absent and unlisted git siblings are skipped offline")
    assert not stale.exists()
    assert not (root / "root-sibling/.cargo/config.toml").exists()
    print("PASS dependency-free consumers get no file and stale marked files are removed")
    workspace_patches = tomllib.loads((wc / ".cargo/config.toml").read_text())["patch"]
    assert "actual_root" in workspace_patches["https://example.invalid/root"]
    assert "actual_beta" in workspace_patches["https://example.invalid/workspace"]
    print("PASS workspace inheritance, member, target, dev and build dependency tables")
    original, mtime = config.read_bytes(), config.stat().st_mtime_ns
    output = generate()
    assert f"unchanged: {config}" in output and "No files written." in output
    assert config.read_bytes() == original and config.stat().st_mtime_ns == mtime
    print("PASS repeat generation preserves bytes, mtime and unchanged reporting")
    git(consumer, "add", "-f", ".cargo/config.toml")
    assert "is tracked" in generate(ok=False)
    assert config.read_bytes() == original
    git(consumer, "rm", "--cached", "-f", ".cargo/config.toml")
    print("PASS tracked config is refused without modification")
    config.write_text("# operator config\n")
    assert "without the ubu-devshell generated marker" in generate(ok=False)
    assert config.read_text() == "# operator config\n"
    config.write_bytes(original)
    stale.write_text("# operator config in dependency-free consumer\n")
    assert "without the ubu-devshell generated marker" in generate(ok=False)
    assert stale.read_text() == "# operator config in dependency-free consumer\n"
    stale.unlink()
    print("PASS unmarked configs are refused, including dependency-free consumers")
    # A typo in a present sibling must fail instead of emitting a dead patch.
    manifest = consumer / "Cargo.toml"
    text = manifest.read_text()
    manifest.write_text(text.replace('package = "actual_root"', 'package = "missing_package"'))
    assert "package missing_package not found" in generate(ok=False)
    assert config.read_bytes() == original
    manifest.write_text(text)
    print("PASS missing package fails without overwriting the consumer config")
    (consumer / ".gitignore").unlink()
    assert f"warn: {consumer} should ignore .cargo/config.toml" in generate()
    print("PASS gitignore warning is preserved")

print("PASS test-patch-config.sh (isolated offline fixtures)")
PY
